---
- name: Modify apache config
  blockinfile:
    dest: /etc/apache2/apache2.conf
    insertbefore: ^#<Directory /srv/>
    marker: "# {mark} ANSIBLE MANAGED BLOCK"
    block: |
      <Directory {{ permpath }}>
        Options Indexes FollowSymLinks
        AllowOverride None
        Require all granted
      </Directory>

- name: Remove the default www settings
  blockinfile:
    dest: /etc/apache2/apache2.conf
    state: absent
    content: |
      <Directory /var/www/>
        Options Indexes FollowSymLinks
        AllowOverride None
        Require all granted
      </Directory>

- name: Install apache modules
  apache2_module:
    state: present
    name: "{{ item }}"
  with_items:
    - rewrite
    - headers
    - env
    - dir
    - mime
    - ssl

- name: Enable apache site
  shell: a2ensite default-ssl

- name: Modify default-ssl.conf
  blockinfile:
    dest: /etc/apache2/sites-available/default-ssl.conf
    insertbefore: </VirtualHost>
    marker: "# {mark} ANSIBLE MANAGED BLOCK"
    block: |
      <Directory {{ permpath }}>
        Options Indexes FollowSymLinks
        AllowOverride All
        Require all granted
      </Directory>
  notify: Restart Apache

- name: Configure postfix
  lineinfile: dest=/etc/postfix/main.cf state=present line='relayhost = relay.t3mx.com'

- name: Copy example config.php to server
  copy: src=files/example_config.php dest={{ ocpath }}/example_config.php

- name: set permissions on www dir
  shell: chmod -R 755 {{ permpath }}
