---
- name: Run only if it hasn't been done already
  stat: path={{ ocroot }}/www/owncloud
  register: st

- name: Create directories
  file: path={{ ocroot }}/www state=directory

- name: Download owncloud tarball
  get_url: url=https://download.owncloud.org/community/owncloud-9.0.2.tar.bz2 dest={{ ocroot }}/owncloud-9.0.2.tar.bz2 validate_certs=no checksum=md5:a0131f5cae2b1503b8de6796487c1bdc

- name: Extract the Tarball
  shell: tar -xjf owncloud-9.0.2.tar.bz2
  args:
    chdir: "{{ ocroot }}"
  when: not st.stat.exists

- name: Copy data to wwwroot
  shell: cp -r {{ ocroot }}/owncloud {{ ocroot }}/www/
  when: not st.stat.exists

- name: set access permissions on www directory
  shell: chmod -R 755 {{ocroot}}/www/owncloud
